apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: backstage
  namespace: backstage-poc
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: backstage
  namespace: backstage-poc
spec:
  source:
    type: Git
    git:
      uri: https://github.com/byron-velasco/enterprise-service-inventory.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 3Gi
  output:
    to:
      kind: ImageStreamTag
      name: backstage:latest
