apiVersion: v1
kind: Secret
metadata:
  name: backstage-postgres-secret
  namespace: backstage-poc
type: Opaque
stringData:
  POSTGRES_USER: backstage
  POSTGRES_PASSWORD: CAMBIAR_ESTA_CLAVE
  POSTGRES_DB: backstage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backstage-postgres-pvc
  namespace: backstage-poc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-postgres
  namespace: backstage-poc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-postgres
  template:
    metadata:
      labels:
        app: backstage-postgres
    spec:
      containers:
        - name: postgres
          image: registry.redhat.io/rhel9/postgresql-15:latest
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: backstage-postgres-secret
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRESQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: backstage-postgres-secret
                  key: POSTGRES_DB
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: backstage-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: backstage-postgres
  namespace: backstage-poc
spec:
  selector:
    app: backstage-postgres
  ports:
    - port: 5432
      targetPort: 5432
